academia/academia/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('api/', include('api.urls')),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('core.urls', namespace="core")),
    path('admin/', admin.site.urls),
]

academia/api/urls.py
from django.conf.urls import include
from django.urls import path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('exercicios', views.ExercicioViewSet)
router.register('treinamentos', views.TreinamentoViewSet)
router.register('logagua', views.LogAguaViewSet)
router.register('logaguadiario', views.LogAguaDiarioViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

academia/core/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('nova_conta/', views.RegistrationView.as_view(), name='nova_conta'),
    path('info_pessoal/', views.info_pessoal, name='info_pessoal'),
    path('exercicio/', views.exercicio, name='exercicio'),
    path('exercicios/', views.exercicios, name='exercicios'),
    path('exercicio/<int:id>/', views.exercicio_edit, name='exercicio_edit'),
    path('treinamento/', views.treinamento, name='treinamento'),
    path('treinamentos/', views.treinamentos, name='treinamentos'),
    path('treinamento/<int:id>/', views.treinamento_edit, name='treinamento_edit'),
    path('consumo_agua/', views.consumo_agua, name='consumo_agua'),
    path('treinamento/delete', views.treinamento_delete, name='treinamento_delete'),
    path('exercicio/delete', views.exercicio_delete, name='exercicio_delete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('relatorio/agua', views.relatorio_agua, name='relatorio_agua'),
    path('humor/', views.humor, name='humor'),
]

academia/core/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.conf import settings
from academia.settings import BASE_DIR


class EmailUserManager(BaseUserManager):
    def create_user(self, *args, **kwargs):
        email = kwargs["email"]
        email = self.normalize_email(email)
        password = kwargs["password"]
        kwargs.pop("password")

        if not email:
            raise ValeuError(_('Necessário um email válido'))

        user = self.model(**kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, *args, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class MyUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(
        verbose_name=_('Email'),
        unique=True,
    )
    first_name = models.CharField(
        verbose_name=_('Nome'),
        max_length=50,
        blank=False,
        help_text=_('Informe seu nome'),
    )
    last_name = models.CharField(
        verbose_name=_('Sobrenome'),
        max_length=50,
        blank=False,
        help_text=_('Informe seu sobrenome'),
    )
    altura = models.CharField(
        verbose_name=_('Altura em cm'),
        max_length=6,
        blank=True,
    )
    peso = models.CharField(
        verbose_name=_('Peso em kg'),
        max_length=7,
        blank=True,
    )
    imc = models.DecimalField(
        verbose_name=_('IMC - Indice de massa corporal'),
        max_digits=5,
        decimal_places=3,
        blank=True,
        null=True,
    )
    agua = models.CharField(
        verbose_name=_('Quantidade minima de consumo de água por dia'),
        max_length=10,
        blank=True,
        null=True,
    )
    consumo_agua = models.CharField(
        verbose_name=_('Consumo de água hoje'),
        max_length=10,
        blank=True,
        null=True,
    )
    nascimento = models.CharField(
        verbose_name=_('Data de nascimento'),
        max_length=10,
    )
    idade = models.IntegerField(
        verbose_name=_('Idade'),
        blank=True,
        null=True,
    )
    genero = models.CharField(
        max_length=3,
        choices=settings.GENERO_CHOICES,
        default='1',
    )
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    objects = EmailUserManager()


class Exercicio(models.Model):
    exercicio = models.CharField(
        'Exercicio', max_length=150
    )
    musculo = models.CharField(
        max_length=8,
        choices=settings.MUSCULO_CHOICES,
        default='1',
    )
    usuario = models.name = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.exercicio

    def __repr__(self):
        return self.exercicio

    class Meta:
        ordering = ['exercicio']
        verbose_name = 'Exercicio'
        verbose_name_plural = 'Exercicios'


class Treinamento(models.Model):
    data = models.CharField(
        verbose_name=_('Data'),
        max_length=15,
    )

    exercicio = models.ForeignKey(
        Exercicio,
        on_delete=models.CASCADE,
        verbose_name=_('Exercício'),
    )
    series = models.IntegerField(
        verbose_name=_('Quantidade de series'),
        blank=True,
        null=True,
        default='-',
    )
    repeticao = models.IntegerField(
        verbose_name=_('Repetições por series'),
        blank=True,
        null=True,
        default='-',
    )
    tempo = models.CharField(
        verbose_name=_('Tempo gasto no exercicio'),
        max_length=10,
        blank=True,
        null=True,
        default='-',
    )
    distancia = models.CharField(
        verbose_name=_('Distancia percorrida'),
        max_length=10,
        blank=True,
        null=True,
        default='-',
    )
    peso = models.CharField(
        verbose_name=_('Peso em kg'),
        max_length=7,
        blank=True,
        null=True,
        default='-',
    )

    usuario = models.name = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.email

    def __repr__(self):
        return self.usuario.email

    class Meta:
        ordering = ['exercicio']
        verbose_name = 'Treinamento'
        verbose_name_plural = 'Treinamentos'


class LogAgua(models.Model):
    consumo_agua = models.CharField(
        verbose_name=_('Consumo de água em ml'),
        max_length=10,
        blank=True,
        null=True,
    )

    data = models.DateTimeField()

    usuario = models.name = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.first_name

    def __repr__(self):
        return self.usuario.first_name

    class Meta:
        ordering = ['id']
        verbose_name = 'Log consumo de agua'
        verbose_name_plural = 'Logs consumo de agua'


class LogAguaDiario(models.Model):
    consumo_agua_dia = models.CharField(
        verbose_name=_('Consumo de água em ml'),
        max_length=10,
        blank=True,
        null=True,
    )

    data = models.DateTimeField()

    usuario = models.name = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.first_name

    def __repr__(self):
        return self.usuario.first_name

    class Meta:
        ordering = ['id']
        verbose_name = 'Log consumo de agua diario'
        verbose_name_plural = 'Logs consumo de agua diario'


class Humor(models.Model):
    humor = models.CharField(
        max_length=8,
        choices=settings.HUMOR_CHOICES,
        default='1',
    )

    data = models.DateTimeField()

    usuario = models.name = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.humor
    
    def __repr__(self):
        return self.usuario.first_name

    class Meta:
        ordering = ['-id']
        verbose_name = 'Registro de humore diario'
        verbose_name_plural = 'Registros de humores diario'

academia/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import MyUser, Exercicio, Treinamento, LogAgua
from django.conf import settings
from academia.settings import BASE_DIR


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Nome'
            }
        )
    )
    last_name = forms.CharField(label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Sobrenome'
            }
        )
    )
    email = forms.EmailField(label='',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Email'
            }
        )
    )

    password1 = forms.CharField(label='',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Senha'
            }
        )
    )

    password2 = forms.CharField(label='',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Confirmar senha'
            }
        )
    )

    class Meta:
        model = MyUser
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']


class ExercicioForm(forms.ModelForm):
    exercicio = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Exercicio'
            }
        )
    )

    musculo = forms.ChoiceField(
        choices=settings.MUSCULO_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Exercicio
        fields = ['exercicio', 'musculo']


class TreinamentoForm(forms.ModelForm):
    def __init__(self, usuario, *args, **kwargs):
        super(TreinamentoForm, self).__init__(*args, **kwargs)
        self.usuario = usuario
        self.fields['exercicio'].queryset = Exercicio.objects.filter(usuario=self.usuario)

    def save(self, commit=True):
        treinamento = super(TreinamentoForm, self).save(commit=False)
        treinamento.usuario = self.usuario

        if commit:
            treinamento.save()
        
        return treinamento


    data = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Data: dd/mm/aaaa', 'type': 'date'
            }
        )
    )

    exercicio = forms.ModelChoiceField(queryset=Exercicio.objects.all(),
        label='',
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    series = forms.IntegerField(required=False,
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Séries'
            }
        )
    )

    repeticao = forms.IntegerField(required=False,
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Repetições por série'
            }
        )
    )

    tempo = forms.CharField(required=False,
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Tempo gasto por série em minutos'
            }
        )
    )

    distancia = forms.CharField(required=False,
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Distancia percorrida em KM'
            }
        )
    )

    peso = forms.CharField(required=False,
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Carga em KG usado no exercicio'
            }
        )
    )

    class Meta:
        model = Treinamento
        fields = ['data', 'exercicio', 'series', 'repeticao', 'tempo', 'distancia', 'peso']

    
class AguaForm(forms.ModelForm):
    consumo_agua = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Consumo de água (em ML)'
            }
        )
    )

    class Meta:
        model = MyUser
        fields = ['consumo_agua']

academia/core/templates/consumo_agua.html
{% extends "base.html" %}

{% block title %}Consumo de água{% endblock %}

{% block content %}

{% include "navbar.html" %}
<div class="col-md-5 col-md-offset-4" align="center">
    <div class="jumbotron col-md-10">
        <h4>Registrar consumo de água</h4>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i></button>
        </form>
    </div>
</div>

{% endblock %}

academia/core/templates/exercicios.html
{% extends "base.html" %}

{% block title %}Exercícios{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading" align="center">
                <h5>Exercicios cadastrados {% if exercicios %}<a class="btn btn-sm btn-success" href="{% url 'core:exercicio' %}"><i class="fas fa-plus"></i></a>{% endif %}</h5>
            </div>
            {% if exercicios %}
                <table class="table">
                    <tr>
                        <th>Exercicio</th>
                        <th>Musculo</th>
                        <th>Ações</th>
                    </tr>
                    {% for exercicio in exercicios %}
                    <tr>
                        <td>{{ exercicio.exercicio }}</td>
                        {% if exercicio.musculo == '1'  %}
                            <td>Abdome</td>
                        {% elif exercicio.musculo == '2'  %}
                            <td>Bíceps</td>
                        {% elif exercicio.musculo == '3'  %}
                            <td>Costas</td>
                        {% elif exercicio.musculo == '4'  %}
                            <td>Peito</td>
                        {% elif exercicio.musculo == '5'  %}
                            <td>Pernas</td>
                        {% elif exercicio.musculo == '6'  %}
                            <td>Tríceps</td>
                        {% elif exercicio.musculo == '7'  %}
                            <td>Ombros</td>
                        {% elif exercicio.musculo == '8'  %}
                            <td>Nádegas</td>
                        {% elif exercicio.musculo == '9' %}
                            <td>Antebraço</td>
                        {% elif exercicio.musculo == '10' %}
                            <td>Eretos da espinha</td>
                        {% endif %}
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-sm btn-primary" href="{% url 'core:exercicio_edit' exercicio.pk %}"><i class="fas fa-pencil-alt"></i></a>
                                <a class="btn-delete btn btn-sm btn-danger" name="{{ exercicio.id }}"><i class="fas fa-trash-alt"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            {% else %}
                <div class="panel-body" align="center">
                    <h6>Nenhum exercicio cadastrado <a class="btn btn-sm btn-success" href="{% url 'core:exercicio' %}"><i class="fas fa-plus"></i></a></h6>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<div id="modalDelete" class="modal fade">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times</span>
                </button>
                <h3 id="modal-title" class="modal-title text-center"></h3>
            </div>

            <div id="modal-body" class="modal-body" align="center"></div>
            <input type="hidden" id="id-exercicio" />

            <div class="modal-footer">
                <button id="btn-nao" type="button" class="btn btn-sm btn-danger" data-dismiss="modal">
                </button>
                <button id="btn-sim" type="button" class="btn btn-sm btn-success">
                    <i class="fas fa-check" aria-hidden="true"></i> Sim
                </button>
            </div>

        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{% load static %}
<script src="{% static '/core/js/exercicios.js' %}"></script>
{% endblock %}

academia/core/templates/home.html
{% extends "base.html" %}

{% block title %}Academia{% endblock %}

{% block content %}

{% if user.is_authenticated %}
{% include "navbar.html" %}
<div class="col-md-8 col-md-offset-2" align="center">
    <div class="bs-callout bs-callout-primary">
        <p>Seja bem vindo {% if user.is_authenticated %}{{ user.first_name }}{% else %}usuário anônimo{% endif %}</p>
        {% for usuario in usuario %}
            {% if usuario.imc is not None %}
                Peso ideal: {{ peso_ideal }} - 
                {% if peso_abaixo == True %}
                    Ganhe {{ diferenca_peso }} kg para chegar ao peso perfeito.
                {% else %}
                    Perca {{ diferenca_peso }} kg para chegar ao peso perfeito.
                {% endif %}
                {% if usuario.imc < 18.6 %}
                    <p align="center">Seu IMC: {{usuario.imc}} - Abaixo do peso</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning" style="width: 10%"></div>
                    </div>
                {% elif usuario.imc >= 18.6 and usuario.imc <= 24.9 %}
                    <p align="center">Seu IMC: {{usuario.imc}} - Peso ideal</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped" style="width: 100%"></div>
                    </div>
                {% elif usuario.imc >= 25.0 and usuario.imc <= 29.9 %}
                    <p align="center">Seu IMC: {{usuario.imc}} - Levemente acima do peso</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: 70%"></div>
                    </div>
                {% elif usuario.imc >= 30.0 and usuario.imc <= 34.9 %}
                    <p align="center">Seu IMC: {{usuario.imc}} - Obesidade grau 1</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-danger progress-bar-striped" style="width: 80%"></div>
                    </div>
                {% elif usuario.imc >= 35.0 and usuario.imc <= 39.9 %}
                    <p align="center">Seu IMC: {{usuario.imc}} - Obesidade grau 2 (severa)</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-danger progress-bar-striped" style="width: 90%"></div>
                    </div>
                {% else %}
                    <p align="center">Seu IMC: {{usuario.imc}} - Obesidade grau 3 (mórbida)</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-danger progress-bar-striped" style="width: 100%"></div>
                    </div>
                {% endif %}
            {% else %}
                <p align="center">Acesse para concluir seu cadastro <a class="btn btn-sm" href="{% url 'core:info_pessoal' %}"><i class="fa fa-share"></i></a></p> 
            {% endif %}
            {% if usuario.agua is not None %}
                <p>Quantidade minima de consumo de água por dia {{ usuario.agua }} ml</p>
                {% if consumo_diario == False %}
                    Sem registros (valor referente ao último dia em que houve registros)
                {% else %}
                    Último consumo diário: {{ consumo_diario }} ml (valor referente ao último dia em que houve registros)
                {% endif %}
                {% if acima_do_minimo == False %}
                    {% if usuario.agua == usuario.consumo_agua %}
                        <p>Parabéns! Você ja consumiu o minimo de água necessário hoje. <a href="{% url 'core:consumo_agua' %}" class="btn btn-sm btn-info"><i class="fa fa-tint"></i></a></p>
                    {% else %}
                        <p>Consumido hoje {% if usuario.consumo_agua is not None %}{{ usuario.consumo_agua }}{% else %} 0 {% endif %} ml, resta {{ agua }} ml <a href="{% url 'core:consumo_agua' %}" class="btn btn-sm btn-warning"><i class="fa fa-tint"></i></a></p>
                    {% endif %}
                {% else %}
                    <p>Consumido hoje {% if usuario.consumo_agua is not None %}{{ usuario.consumo_agua }}{% else %} 0 {% endif %} ml, você ja consumiu {{ agua }} ml acima do minimo necessário hoje <a href="{% url 'core:consumo_agua' %}" class="btn btn-sm btn-info"><i class="fas fa-tint"></i></a></p>
                {% endif %}
                {% if percentual < 40 %}
                    <div class="progress">
                        <div class="progress-bar progress-bar-danger progress-bar-striped" style="width: {{percentual}}%"></div>
                    </div>
                {% elif percentual > 40 and percentual < 65 %}
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: {{percentual}}%"></div>
                    </div>
                {% else %}
                    <div class="progress">
                        <div class="progress-bar progress-bar-info progress-bar-striped" style="width: {{percentual}}%"></div>
                    </div>
                {% endif %}
                <p>{{ percentual }}% <i class="fas fa-tint"></i></p>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% else %}
{% include "navbar.html" %}
<div class="col-md-6 col-md-offset-3" align="center">
    <div class="jumbotron">
        <h4>Faça <a class="text-warning" href="{% url 'core:login' %}">login</a> ou crie uma <a class="text-warning" href="{% url 'core:nova_conta' %}">nova conta</a> para acessar</h4>
    </div>
</div>
{% endif %}

{% endblock %}

academia/core/templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'core:home' %}">Academia {% if user.is_authenticated %}de {{user.first_name}} <input id="id_usuario" type="hidden" value="{{user.pk}}" /> {% endif %}</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {% if user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-dumbbell"></i> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'core:exercicio' %}"><i class="fas fa-plus"></i> Cadastrar exercicio</a></li>
            <li><a href="{% url 'core:exercicios' %}"><i class="fas fa-list-ul"></i> Lista de exercícios</a></li>
            <li><a href="{% url 'core:treinamento' %}"><i class="fas fa-plus"></i> Registrar treinamento</a></li>
            <li><a href="{% url 'core:treinamentos' %}"><i class="fas fa-clipboard-list"></i> Treinamentos</a></li>
            <li><a href="{% url 'core:humor' %}"><i class="far fa-grin"></i> Humor</a></li>

            <li role="separator" class="divider"></li>
            <li><a href="{% url 'core:dashboard' %}"><i class="fas fa-chart-line"></i> Dashboard</a></li>
            <li><a href="{% url 'core:relatorio_agua' %}"><i class="fas fa-tint"></i> Relatório àgua</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-sliders-h"></i> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'core:info_pessoal' %}"><i class="fas fa-user-edit"></i> Informaçoẽs pessoais</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'core:logout' %}"><i class="fas fa-sign-out-alt"></i> Sair</a></li>
          </ul>
        </li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav">
        <li><a href="{% url 'core:login' %}"><i class="fas fa-sign-in-alt"></i> Login</a></li>
        <li><a href="{% url 'core:nova_conta' %}"><i class="fas fa-user-circle"></i> Criar conta</a></li>
      </ul>
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

academia/core/templates/treinamentos.html
{% extends "base.html" %}

{% block title %}Treinamentos{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading" align="center">
                <h5>Treinamentos {% if treinamentos %}<a class="btn btn-sm btn-success" href="{% url 'core:treinamento' %}"><i class="fas fa-plus"></i></a>{% endif %}</h5>
            </div>
            {% if treinamentos %}
                <table class="table">
                    <tr>
                        <th>Exercicio</th>
                        <th>Séries</th>
                        <th>Repetições</th>
                        <th>Tempo</th>
                        <th>Distancia</th>
                        <th>Carga</th>
                        <th>Musculo trabalhado</th>
                        <th>Data do treinamento</th>
                        <th>Ações</th>
                    </tr>
                    {% for treinamento in treinamentos %}
                    <tr>
                        {% if treinamento.exercicio == '' or treinamento.exercicio is None or treinamento.exercicio == 0 %}
                        <td>-</td>
                        {% else %}
                            <td>{{ treinamento.exercicio }}</td>
                        {% endif %}
                        {% if treinamento.series == '' or treinamento.series is None or treinamento.exercicio == 0 %}
                            <td>-</td>
                        {% else %}
                            <td>{{ treinamento.series }}</td>
                        {% endif %}
                        {% if treinamento.repeticao == '' or treinamento.repeticao is None or treinamento.repeticao == 0 %}
                            <td>-</td>
                        {% else %}
                            <td>{{ treinamento.repeticao }}</td>
                        {% endif %}
                        {% if treinamento.tempo == '' or treinamento.tempo is None or treinamento.tempo == 0 %}
                            <td>-</td>
                        {% else %}
                            <td>{{ treinamento.tempo }}</td>
                        {% endif %}
                        {% if treinamento.distancia == '' or treinamento.distancia in None or treinamento.distancia == 0 %}
                            <td>-</td>
                        {% else %}
                            <td>{{ treinamento.distancia }}</td>
                        {% endif %}
                        {% if treinamento.peso == '' or treinamento.peso is None or treinamento.peso == 0 %}
                            <td>-</td>
                        {% else %}
                            <td>{{ treinamento.peso }} KG</td>
                        {% endif %}
                        {% if treinamento.exercicio.musculo == '1' %}
                            <td>Abdome</td>
                        {% elif treinamento.exercicio.musculo == '2' %}
                            <td>Bíceps</td>
                        {% elif treinamento.exercicio.musculo == '3' %}
                            <td>Costas</td>
                        {% elif treinamento.exercicio.musculo == '4' %}
                            <td>Peito</td>
                        {% elif treinamento.exercicio.musculo == '5' %}
                            <td>Pernas</td>
                        {% elif treinamento.exercicio.musculo == '6' %}
                            <td>Tríceps</td>
                        {% elif treinamento.exercicio.musculo == '7' %}
                            <td>Ombros</td>
                        {% elif treinamento.exercicio.musculo == '8' %}
                            <td>Nádegas</td>
                        {% elif treinamento.exercicio.musculo == '9' %}
                            <td>Antebraço</td>
                        {% elif treinamento.exercicio.musculo == '10' %}
                            <td>Eretos da espinha</td>
                        {% endif %}
                        {% if treinamento.data == '' or treinamento.data is None or treinamento.data == 0 %}
                            <td>-</td>
                        {% else %}
                            <td>{{ treinamento.data }}</td>
                        {% endif %}
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-sm btn-primary" href="{% url 'core:treinamento_edit' treinamento.id %}"><i class="fas fa-pencil-alt"></i></a>
                                <a class="btn-delete btn btn-sm btn-danger" name="{{ treinamento.id }}"><i class="fas fa-trash-alt"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            {% else %}
                <div class="panel-body" align="center">
                    <h6>Nenhum treinamento cadastrado <a class="btn btn-sm btn-success" href="{% url 'core:treinamento' %}"><i class="fas fa-plus"></i></a></h6>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<div id="modalDelete" class="modal fade">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times</span>
                </button>
                <h3 id="modal-title" class="modal-title text-center"></h3>
            </div>

            <div id="modal-body" class="modal-body" align="center"></div>
            <input type="hidden" id="id-treinamento" />

            <div class="modal-footer">
                <button id="btn-nao" type="button" class="btn btn-sm btn-danger" data-dismiss="modal">
                </button>
                <button id="btn-sim" type="button" class="btn btn-sm btn-success">
                    <i class="fas fa-check" aria-hidden="true"></i> Sim
                </button>
            </div>

        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{% load static %}
<script src="{% static '/core/js/treinamentos.js' %}"></script>
{% endblock %}